<a href="https://colab.research.google.com/github/alimoorreza/CS167-SP26-Notebook-4/blob/main/Notebook4_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook \#4

## Part 1:
**1.) Using scikit learn (sklearn)** You must run at least 6 variations of the algorithms and display their results using an appropriate regression metric (again, use the scikit-learn modules). I will be looking for the following to be included in your comparison:

*   k-Nearest-Neighbor with a **small value of k**
*   k-Nearest-Neighbor with a **large value of k**
*   **weighted k-Nearest-Neighbor** with a **small value of k** (the same one you used for the unweighted version)
*  **weighted k-Nearest-Neighbor** with a **large value of k** (the same one you used for the unweighted version)
*   a **decision tree with default** parameter values
*   a **decision tree**, setting some kind of parameter that results in a **smaller tree**

You will need to use the documentation for sklearn for this Notebook. Here are some helpful links:
* [K Neighbors Regressor](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html)
* [Decision Tree Regressor](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html)

In [ ]:
# load in the data and necessary libraries
import sklearn
import pandas
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import neighbors
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')
wine = pandas.read_csv('/content/drive/MyDrive/cs167_sp26/datasets/winequality-white.csv') # change this to match your dataset directory
wine.head()

Mounted at /content/drive

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
# Split the data into the training data and testing data

target= 'quality'
predictors = wine.columns.drop(target)
train_data, test_data, train_sln, test_sln = train_test_split(wine[predictors], wine[target], test_size = 0.2, random_state=41)
train_data.head()

      fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
24              6.9              0.40         0.14  ...  3.43       0.63     9.70
728             6.4              0.57         0.02  ...  3.46       0.68     9.50
1366            7.3              0.74         0.08  ...  3.24       0.50     9.80
1413            9.9              0.57         0.25  ...  3.04       0.90    10.10
1456            6.0              0.54         0.06  ...  3.30       0.50    10.55

[5 rows x 11 columns]

In [ ]:
# kNN with small k

In [ ]:
# kNN with large k

In [ ]:
# w-knn with small k

In [ ]:
# w-knn with large k

In [ ]:
# decision tree with default paramters

In [ ]:
# decision tree with some kind of parameter that (hopefully) results in a smaller tree

## Part 2: kNN on Normalized data
**2.)** Normalize the data and run a k-Nearest-Neighbor algorithm on it. (use the StandardScalar from sklearn)

In [ ]:
# normalize the data


# run a knn

## Part 3:
**3.)**Use a Markup cell to answer the following questions:

- What algorithm performed better? kNN or Decision Trees? Why do you think this was the case?
- What effect did normalizing the data have on your results? Explain.